### ISSUE TITLE
Update coverage and Pypi up to py3.10

### ISSUE THREAD

**Issue by emirkmo** [ForeverWintr/metafunctions#19]
Python versions 3.8, 3.9, and 3.10 are out, and some of them are becoming ubiquitous. It's important to verify nothing is broken and update pypi to reflect these changes.

**Comment by ForeverWintr** [comment]
These changes have been completed, and 1.1.1 is now available on [pypi](https://pypi.org/project/metafunctions/1.1.1/
).

**Comment by emirkmo** [comment]
Awesome.  Thanks for getting around to this!
