### ISSUE TITLE
Argument in the middle of pipeline

### ISSUE THREAD

**Issue by xVapino** [ForeverWintr/metafunctions#25]
Hi, first of all, it's awesome work done here. 
Quick question though, how can I pass or add more arguments in the middle of pipeline,

for example,

```python
@node
do foo(a):
    # some processing
    return a

@node
do bar(b):
    # some processing
    return b

@node
do cool(a,b,c,d):
     # some processing
     return result

f = (a & b ......) | star(cool)

f()
```

how to execute a & b and collect their result and pass them to cool along with c,d arguments.

**Comment by ForeverWintr** [comment]
Thank you for the kind words. :)

I'm not sure if I am understanding your intent correctly. Do you want to include `foo` and `bar` in your pipeline, and pass arguments for `c` and `d` separately? Here's one way to do that:

```python
@node
def foo(a):
    # some processing
    return a

@node
def bar(b):
    # some processing
    return b

@node
def cool(a, b, c, d):
    # some processing
    return (a, b, c, d)

f = (foo & bar & "arg_c" & "arg_d") | star(cool)
assert f('a', 'b') == ('a', 'b', 'arg_c', 'arg_d')
```

I see the documentation could be improved to mention this!

**Comment by xVapino** [comment]
Hi, thanks. This is exactly what I was looking for.
